# HOME
logoHeader: "assets/images/logo-header.svg"
realName: "ERNESTO A. NAPPI"
freelancerSlogan: "A Freelance UI Designer y Web Developer"
freelancerImage: "assets/images/banner/hero.png"
socialNetwork:
    facebook: "#"
    twitter: "#"
    behance: "#"
    linkedin: "#"

# ABOUT
whoIAm: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
birth: "0 Januay 0000"
email: "email@domain.com"
phone: "+00 0 00 00000000"
location: "0000, Federal District, DD"
skills:
  - name: "HTML"
    percentage: "80"
  - name: "CSS"
    percentage: "60"
  - name: "Photoshop"
    percentage: "50"
  - name: "Sketch"
    percentage: "90"


# SERVICES
whatIDo: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
services:
  - icon: "lni-code-alt"
    title: "Web Design"
    description: "Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit enimdicta sunt."
  - icon: "lni-code-alt"
    title: "Web Design"
    description: "Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit enimdicta sunt."
  - icon: "lni-code-alt"
    title: "Web Design"
    description: "Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit enimdicta sunt."
  - icon: "lni-code-alt"
    title: "Web Design"
    description: "Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit enimdicta sunt."
  - icon: "lni-code-alt"
    title: "Web Design"
    description: "Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit enimdicta sunt."
  - icon: "lni-code-alt"
    title: "Web Design"
    description: "Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit enimdicta sunt."

# CALL TO ACTION
callToActionBackground: "assets/images/call-to-action.jpg"
callToAction: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
urlOfCurriculumVitae: "#"

# PORTFOLIO
myRecentWorks: "Nunc id dui at sapien faucibus fermentum ut vel diam. Nullam tempus, nunc id efficitur sagittis, urna est ultricies eros, ac porta sem turpis quis leo."
urlMoreWorks: "#"
works:
  - thumbnail: "assets/images/work/w-1.jpg"
    image: "assets/images/work/w-1.jpg"
    title: "Product Design"
    link: "#"
  - thumbnail: "assets/images/work/w-1.jpg"
    image: "assets/images/work/w-1.jpg"
    title: "Product Design"
    link: "#"
  - thumbnail: "assets/images/work/w-1.jpg"
    image: "assets/images/work/w-1.jpg"
    title: "Product Design"
    link: "#"
  - thumbnail: "assets/images/work/w-1.jpg"
    image: "assets/images/work/w-1.jpg"
    title: "Product Design"
    link: "#"
  - thumbnail: "assets/images/work/w-1.jpg"
    image: "assets/images/work/w-1.jpg"
    title: "Product Design"
    link: "#"
  - thumbnail: "assets/images/work/w-1.jpg"
    image: "assets/images/work/w-1.jpg"
    title: "Product Design"
    link: "#"

# CONTACT
contactMe: "Nunc id dui at sapien faucibus fermentum ut vel diam. Nullam tempus, nunc id efficitur sagittis, urna est ultricies eros, ac porta sem turpis quis leo."
map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3283.0374232683293!2d-58.42937134960413!3d-34.62849456621971!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcca528cbfeb3b%3A0x3968ab1a910cea6e!2sZuvir%C3%ADa%2064%2C%20C1424CKB%20CABA!5e0!3m2!1ses-419!2sar!4v1580320671559!5m2!1ses-419!2sar"

# FOOTER
footer: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci- didunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exe- rcitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
logoFooter: "assets/images/logo-footer.svg"

# WEBSITE CONFIG
copyYear: "2020"
poweredBy:
  name: eanappi
  url: https://eanappi.top
